In [1]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
print(f"MPS available: {torch.backends.mps.is_available()}")
print(f"MPS built: {torch.backends.mps.is_built()}")

# Get system info
!system_profiler SPHardwareDataType | grep "Chip"
!sysctl -n machdep.cpu.brand_string

# Check memory
!system_profiler SPHardwareDataType | grep "Memory"

MPS available: True
MPS built: True
2026-06-20 14:10:36.438 system_profiler[17390:786425] hw.cpufamily: 0x6f5129ac
      Chip: Apple M4
Apple M4
2026-06-20 14:10:36.971 system_profiler[17395:786446] hw.cpufamily: 0x6f5129ac
      Memory: 16 GB


In [3]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("MPS available! Using Apple GPU")
else:
    device = torch.device("cpu")
    print("MPS not available, using CPU")

MPS available! Using Apple GPU


In [11]:
print(torch.__version__)

2.8.0


# Tensors

In [ ]:
# scalar
# scalar= torch.tensor(1, dtype=torch.float16, device=device).detach()
scalar= torch.tensor(1)
scalar.ndim , scalar.item() 

(0, 1, torch.Size([]))

In [ ]:
# vector
vector= torch.tensor([7,7])
vector.tolist() , vector.shape

([7, 7], torch.Size([2]))

In [61]:
# MATRIX
MATRIX= torch.tensor([[1,-1], 
                      [2,-2]])
MATRIX.tolist(), MATRIX.ndim, MATRIX.shape


([[1, -1], [2, -2]], 2, torch.Size([2, 2]))

In [69]:
# Tensor
ts= torch.zeros(3,2,1)
ts.shape, ts.tolist()

(torch.Size([3, 2, 1]), [[[0.0], [0.0]], [[0.0], [0.0]], [[0.0], [0.0]]])

In [78]:
# Random tensors
gn= torch.Generator().manual_seed(42)
rts= torch.rand(3,4, generator=gn)
rts, rts.ndim

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 2)

In [82]:
# Random tensor
rtsi= torch.rand(400,400,3)
rtsi.shape, rtsi.ndim

(torch.Size([400, 400, 3]), 3)

In [74]:
import time

#time test tensor creation
start_time= time.time()
tensor1= torch.tensor([[1,-1],[2,-2]])
print(f'time to create a tensor without numpy: {time.time()-start_time}')
print(tensor1)

start_time= time.time()
tensor2= torch.tensor(np.array([[1,-1],[2,-2]]))
print(f'time to create a tensor with numpy: {time.time()-start_time}')
print(tensor2)

time to create a tensor without numpy: 0.00010371208190917969
tensor([[ 1, -1],
        [ 2, -2]])
time to create a tensor with numpy: 0.00023698806762695312
tensor([[ 1, -1],
        [ 2, -2]])


In [11]:
# Create a range of tensors and tensors-like
one_to_ten=torch.arange(start=1,end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
#Creating tensors-like
ten_zeros= torch.zeros_like(one_to_ten, dtype=None)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# tensors data type
ten_zeros.dtype, one_to_ten.dtype

(torch.int64, torch.int64)

In [21]:
# data type conversion
tens_zeros_float16= ten_zeros.type(torch.float16)
tens_zeros_float16.dtype

torch.float16

In [26]:
# Getting information from tensors
tens_zeros_float16.dtype, tens_zeros_float16.shape, tens_zeros_float16.device

(torch.float16, torch.Size([10]), device(type='cpu'))