In [2]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [3]:
print(f"MPS available: {torch.backends.mps.is_available()}")
print(f"MPS built: {torch.backends.mps.is_built()}")

# Get system info
!system_profiler SPHardwareDataType | grep "Chip"
!sysctl -n machdep.cpu.brand_string

# Check memory
!system_profiler SPHardwareDataType | grep "Memory"

MPS available: True
MPS built: True
2026-06-21 10:15:07.363 system_profiler[25072:1000503] hw.cpufamily: 0x6f5129ac
      Chip: Apple M4
Apple M4
2026-06-21 10:15:07.846 system_profiler[25077:1000524] hw.cpufamily: 0x6f5129ac
      Memory: 16 GB


In [4]:
if torch.backends.mps.is_available():
    device = torch.device("mps")
    print("MPS available! Using Apple GPU")
else:
    device = torch.device("cpu")
    print("MPS not available, using CPU")

MPS available! Using Apple GPU


In [5]:
print(torch.__version__)

2.8.0


# Tensors

In [6]:
# scalar
# scalar= torch.tensor(1, dtype=torch.float16, device=device).detach()
scalar= torch.tensor(1)
scalar.ndim , scalar.item() 

(0, 1)

In [7]:
# vector
vector= torch.tensor([7,7])
vector.tolist() , vector.shape

([7, 7], torch.Size([2]))

In [8]:
# MATRIX
MATRIX= torch.tensor([[1,-1], 
                      [2,-2]])
MATRIX.tolist(), MATRIX.ndim, MATRIX.shape


([[1, -1], [2, -2]], 2, torch.Size([2, 2]))

In [9]:
# Tensor
ts= torch.zeros(3,2,1)
ts.shape, ts.tolist()

(torch.Size([3, 2, 1]), [[[0.0], [0.0]], [[0.0], [0.0]], [[0.0], [0.0]]])

In [10]:
# Random tensors
gn= torch.Generator().manual_seed(42)
rts= torch.rand(3,4, generator=gn)
rts, rts.ndim

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 2)

In [11]:
# Random tensor
rtsi= torch.rand(400,400,3)
rtsi.shape, rtsi.ndim

(torch.Size([400, 400, 3]), 3)

In [12]:
import time

#time test tensor creation
start_time= time.time()
tensor1= torch.tensor([[1,-1],[2,-2]])
print(f'time to create a tensor without numpy: {time.time()-start_time}')
print(tensor1)

start_time= time.time()
tensor2= torch.tensor(np.array([[1,-1],[2,-2]]))
print(f'time to create a tensor with numpy: {time.time()-start_time}')
print(tensor2)

time to create a tensor without numpy: 0.00010275840759277344
tensor([[ 1, -1],
        [ 2, -2]])
time to create a tensor with numpy: 0.0021200180053710938
tensor([[ 1, -1],
        [ 2, -2]])


In [13]:
# Create a range of tensors and tensors-like
one_to_ten=torch.arange(start=1,end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Creating tensors-like
ten_zeros= torch.zeros_like(one_to_ten, dtype=None)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
# tensors data type
ten_zeros.dtype, one_to_ten.dtype

(torch.int64, torch.int64)

In [16]:
# data type conversion
tens_zeros_float16= ten_zeros.type(torch.float16)
tens_zeros_float16.dtype

torch.float16

In [17]:
# Getting information from tensors
tens_zeros_float16.dtype, tens_zeros_float16.shape, tens_zeros_float16.device

(torch.float16, torch.Size([10]), device(type='cpu'))

In [ ]:
# Manipulating tensors, tensor operations, python / torch 
tensor= torch.tensor([1,2,3])
tensor + 10 , torch.add(tensor, 10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [ ]:

tensor * 10 , torch.mul(tensor, 10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [25]:
tensor -10 , torch.sub(tensor, 10)

(tensor([-9, -8, -7]), tensor([-9, -8, -7]))

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"equal: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equal: tensor([1, 4, 9])


In [43]:
%%time
# Matric muliplications (dot product)
torch.matmul(tensor, tensor)

CPU times: user 80 µs, sys: 19 µs, total: 99 µs
Wall time: 97 µs


tensor(14)

In [31]:
%%time
value=0
for i in range(len(tensor)):
    value+= tensor[i]* tensor[i]
value

CPU times: user 710 µs, sys: 313 µs, total: 1.02 ms
Wall time: 709 µs


tensor(14)

In [3]:
%%time
rts= torch.rand(400,300)
rts2= torch.rand(300, 700)
torch.matmul(rts, rts2).size()


CPU times: user 1.18 ms, sys: 2.31 ms, total: 3.49 ms
Wall time: 9.14 ms


torch.Size([400, 700])

In [ ]:
torch.mm(rts, rts2) # same as torch.matmul, matrix multiplication

tensor([[71.6872, 71.4717, 70.6485,  ..., 75.3493, 74.5042, 69.6460],
        [77.5923, 78.0073, 76.2364,  ..., 81.4161, 79.1413, 75.5806],
        [78.4736, 79.3876, 78.9392,  ..., 80.3811, 79.4387, 72.1951],
        ...,
        [78.3513, 81.1585, 78.7571,  ..., 78.0840, 82.2499, 77.9118],
        [72.8707, 75.7875, 72.6497,  ..., 76.4173, 77.5209, 75.3250],
        [76.0387, 75.9213, 76.0490,  ..., 76.1249, 77.1773, 71.4627]])

In [14]:
# Matrix transpose swith the axis of a tensor
rts.T .shape, rts.shape, rts.dtype

(torch.Size([300, 400]), torch.Size([400, 300]), torch.float32)

In [17]:
# tensor aggregation, finding mean, max, min ,sum
rts.mean() , rts.min(), rts.max() , rts.sum()

(tensor(0.5009), tensor(1.0073e-05), tensor(1.0000), tensor(60110.9805))

In [18]:
torch.mean(rts), torch.min(rts), torch.max(rts), torch.sum(rts)

(tensor(0.5009), tensor(1.0073e-05), tensor(1.0000), tensor(60110.9805))

In [19]:
# torch mean function does not work with long data type
rts2= rts.type(torch.long)
rts2.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [26]:
# finding the positional min and max
rts.argmin(), rts.argmax(), rts.flatten()[rts.argmin()], rts.flatten()[rts.argmax()]

(tensor(78407), tensor(108020), tensor(1.0073e-05), tensor(1.0000))

In [51]:
# Reshaping, stacking, squeezing, unsqueezing tensors
import torch
x= torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [52]:
# add an extra dimension
# x_reshaped= x.reshape(1,10)
# x_reshaped= x.reshape(10,1)
x_reshaped= x.reshape(5,2)
x_reshaped, x_reshaped.shape


(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [53]:
# change the view, shares the same memory as the original tensor
z= x.view(2,5)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [54]:
#changing the z changes the x
z[0][1]=5
z,x

(tensor([[ 1,  5,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 tensor([ 1,  5,  3,  4,  5,  6,  7,  8,  9, 10]))

In [59]:
# stack tensors on top of each others
# dim =1 horizontally, dim=2 vertically
x_stacked= torch.stack([x, x], dim=1)
x_stacked

tensor([[ 1,  1],
        [ 5,  5],
        [ 3,  3],
        [ 4,  4],
        [ 5,  5],
        [ 6,  6],
        [ 7,  7],
        [ 8,  8],
        [ 9,  9],
        [10, 10]])